#!/usr/bin/env python
from tetos.executor.executor import Executor
from tetos.executor.args_checker import supported_protocols, check_args

import argparse


if __name__ == '__main__':
    args_parser = argparse.ArgumentParser()
    args_parser.add_argument('input_path', nargs=1, help='URL or path to a website or a local file with a playlist. '
                                                         'It should begin with {} for remote files'
                                                         .format(' or '.join(supported_protocols)))
    args = args_parser.parse_args()
    check_args(args)
    Executor(args).execute()
