#!/usr/bin/env python
from tetos.executor.executor import Executor
from tetos.executor.args_checker import supported_protocols

import argparse


if __name__ == '__main__':
    args_parser = argparse.ArgumentParser()
    args_parser.add_argument('input_path', nargs=1, help='URL or path to a website or a local file with a playlist.'
                                                         'The address should begin with {} for a local file'
                                                         .format(' or '.join(supported_protocols)))
    args = args_parser.parse_args()
    Executor(args).execute()
